### ISSUE TITLE
Default task to install components 

### ISSUE THREAD

**Issue by chrisbuttery** [nib-components/generator-nib#3]
@anthonyshort Hey dude what are your thoughts on this?

I'm thinking that the default grunt task should call componentinstall:boot.

``` js
  grunt.registerTask('default', [
    'componentinstall:boot',
    'preboot',
    'boot'
  ]);
```

Since we have access though the proxy for component, there's no need to commit them (apart from 'boot' and anything local). So when a BED clones a project, and npm does a postinstall calling the default grunt task, they get all components installed and then built.

The only downside I see with this is the extra few seconds It'll take to build when running the default task.
The plus side, the BED build script just installs/runs npm and theres less complaining about the "over complicated front-end".

**Comment by anthonyshort** [comment]
That sounds good! I'll update the componentinstall task to not be force by default, so it won't slow down the build at all, it just won't install if they're already installed. Then you can add a `clean` task to remove the `build` and `components` directories if you ever need to "refresh" everything
